zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    filemetadata-service: /filemetadata/**
    storage-service: /storage/**
    api-gateway: /gateway/**

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

# Internationalization
spring.messages.basename: messages/messages

---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://tracing-server:9411
  http:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
