spring:
  profiles: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://tracing-server:9411
  http:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
